### PR TITLE
Gmoccapy Icontheme: Use default icon names

### PR DESCRIPTION
**Pull request by hansu**
I thought it would be nice to have the icon names in the Gmoccapy themes matching the names of the freedesktop icon specification.
That would:
a) make it easier for new themes finding the appropriate icon
b) would enable to use the system theme for non specific icons

BUT: I changed all icons which have counterparts in freedesktop spec. The result was, that gmoccapy neither took the icons from the icontheme nor took the icons from the current system theme. It took the systems icons from the first theme it could find (in my case "Adwaita"). And the symbolic colors do not match. I think because we may haven't the correct StyleContext.

Do you have an idea how we could set the lookup order? So first look if it's avalable in the custom theme, if not then in the selected system theme.

### CODE REVIEW

**Comment by hansu** [comment]
If that wouldn't work having the icon names identical with the names of the freedesktop spec, I think it would be even a benefit if we have names similar to them. For example edit-undo <-> edit_undo. Feel free to change that to not interrupt your workflow ;-)
But that's more like a nice to have and not really important for the ongoing PR. This could also be done later.

**Comment by PeterMue** [comment]
I think the order is already correct but a bit weird.

image
Thats the icon `application-exit`.

IMHO the lookup path ist as follows:

1. Classic Theme
2. hicolor
3. default
4. Adwaita

because first, Classic theme contains no symbolic version of `application-exit` therfore the parent (configured in the classic index.theme Inherits=hicolor) hicolor will be used. But hicolor does also not contain such icon. Then the default theme will be used which is (in the default linuxcnc debian 2.8.2 image) symlinked to Adwaita and there is a symbolic version of the `application-exit` icon.

```bash
➜  ~ find ~/linuxcnc-dev/share/gmoccapy/icons/classic -name 'application-exit*symbolic*'
➜  ~ grep Inherits ~/linuxcnc-dev/share/gmoccapy/icons/classic/index.theme
Inherits=hicolor
➜  ~ find /usr/share/icons/hicolor -name 'application-exit*symbolic*'
➜  ~ grep Inherits /usr/share/icons/hicolor/index.theme
➜  ~ # no inheritance but theres a default folder
➜  ~ find /usr/share/icons/default -name 'application-exit*symbolic*'
➜  ~ # theres nothing in there but a symlinked index.theme
➜  ~ ls -la /usr/share/icons/default
insgesamt 8
drwxr-xr-x  2 root root 4096 Nov 22 22:22 .
drwxr-xr-x 12 root root 4096 Jan 17 10:00 ..
lrwxrwxrwx  1 root root   32 Nov 22 22:22 index.theme -> /etc/alternatives/x-cursor-theme
➜  ~ cat /etc/alternatives/x-cursor-theme
[Icon Theme]
Inherits=Adwaita
➜  ~ find /usr/share/icons/Adwaita -name 'application-exit*symbolic*'
/usr/share/icons/Adwaita/64x64/actions/application-exit-symbolic.symbolic.png
/usr/share/icons/Adwaita/24x24/actions/application-exit-symbolic.symbolic.png
/usr/share/icons/Adwaita/48x48/actions/application-exit-symbolic.symbolic.png
/usr/share/icons/Adwaita/96x96/actions/application-exit-symbolic.symbolic.png
/usr/share/icons/Adwaita/32x32/actions/application-exit-symbolic.symbolic.png
/usr/share/icons/Adwaita/16x16/actions/application-exit-symbolic.symbolic.png
/usr/share/icons/Adwaita/scalable/actions/application-exit-symbolic.svg
```

That's because we're forcing the symbolic icons here: https://github.com/PeterMue/linuxcnc/blob/3ca04e11ec9aa371a59d1c622129133bbceccebd/src/emc/usr_intf/gmoccapy/gmoccapy.py#L4555

**Comment by PeterMue** [comment]
> If that wouldn't work having the icon names identical with the names of the freedesktop spec, I think it would be even a benefit if we have names similar to them. For example edit-undo <-> edit_undo. Feel free to change that to not interrupt your workflow ;-)
> But that's more like a nice to have and not really important for the ongoing PR. This could also be done later.

I think it makes sense to align them with the spec but we have to be careful to not misuse the intention.
For example I think edit-undo shouldn't be the same as "go back to previous menu level" (like "img_ref_menu_close",      "back_to_app", although "back_to_app" is also not good semantic)

**Comment by hansu** [comment]
>I think it makes sense to align them with the spec but we have to be careful to not misuse the intention.
For example I think edit-undo shouldn't be the same as "go back to previous menu level" (like "img_ref_menu_close", "back_to_app", although "back_to_app" is also not good semantic)

Yes, I agree. But still looks suitable even if the name doesn't fit at all :smile: 

grafik

`go-last` and  `window-close` would work. But the name is still not really suitable.

**Comment by hansu** [comment]
>That's because we're forcing the symbolic icons here: 

Ahh yes that's it! You are the expert :wink: 
Not forcing it makes it work as expected. But then you symbolic themes don't work.
Can't we define somewhere in the icon theme whether it should be used as symbolic or not?
I mean we could add an addition setting for that, but I think that would only confuse the user.

**Pull request closed without merging**
